-- Insertar hoteles
INSERT INTO be_alap.hotel (country,
regime,
audit,
hotname,
stars,
totalrooms,
floors,
receptionmail,
directionmail,
direction,
geodata,
image,
description,
isactive)

VALUES (1,
		2,
		1,
		'Iberostar Guapo',
		5,
		100,
		5,
		'reception@mail.xd',
		'direction@mail.lmao',
		'Carrer del mig 3',
		231231.121,
		'urlIberostarGuapo.png',
		'Hotel bien guapo en a pie de playa',
		TRUE
),
		(1,
		5,
		3,
		'Melià Feo',
		1,
		25,
		2,
		'reception@mail.xd',
		'direction@mail.lmao',
		'Carrer del sobra 2',
		231231.121,
		'urlMeliaFeo.png',
		'Hotel bien feo en Son Gotleu',
		TRUE
)

-- Gente
INSERT INTO be_alap.registeredclient (country,
										natdoc,
										genid,
										treatment,
										cname,
										surname,
										birthdate,
										email,
										nationality,
										adress,
										zipcode,
										residence)
VALUES 								(1,
									1,
									2,
									3,
									'Antonia',
									'Demonia',
									now(),
									'toniademonia@scam.exe',
									'ES',
									'C/ Me la invento 69',
									07001,
									'Madrid');

-- Hacer reserva
INSERT INTO be_alap.booking (hotel,
							regclient,
							nonclient,
							room,
							payment,
							audit,
							status,
							bookdate,
							entrydate,
							exitdate,
							numnights,
							numadults,
							numbabies,
							numrooms,
							taxbase,
							totalprice)
					
					VALUES (1,
							1,
							NULL,
							1,
							3,
							1,
							1,
							now(),
							now(),
							now(),
							5,
							2,
							0,
							0,
							1,
							129.99,
							176.96
							)			